/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ejercicio1contactos;

import javax.swing.*;
import java.util.Date;

public class App {
    public static void main(String[] args) {
        Agenda ag = new Agenda();
        JFrame window = new JFrame("Agenda");
        Frame.Pantalla panel = new Frame.Pantalla(ag);

        window.add(panel);
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.setResizable(false);
        window.setSize(500,500);
        window.setLocationRelativeTo(null);
        window.setVisible(true);

        Persona p = new Persona("Diego", "Carrillo", 20);
        ContactoT1 c1 = new ContactoT1(p, 85543228, "TEC", "86124272");
        ContactoT2 c2 = new ContactoT2(p, 89654331, "PRIMO", "Canalla");
        EventoT1 e1 = new EventoT1("Descripcion", "nombre", new Date(), "CRC", "Diego");
        EventoT2 e2 = new EventoT2("Descripcion", "nombre", new Date(), "Arroyo");
        ag.addEvento(e1);
        ag.addEvento(e2);
        ag.addContacto(c1);
        ag.addContacto(c2);

    }
}
